#pragma once

int MedalDetailExistHook(int* params);
int MedalDetailFilenameHook(int* params);
int FamilyMedalDescriptionHook(int* params);
int CustomMoviesOnPoints1Hook(int* params);
int CustomMoviesOnPointsPlayHook(int* params);
int CustomPointsCheckHook(int* params);
int LoadGameStateHook(int* params);
int FreeGameStateHook(int* params);
int DrawConcoursePlanetHook(int* params);
int DrawConcourseDoorsHook(int* params);
int TrainDoorRectHook(int* params);
int CombatDoorRectHook(int* params);
int TourDoorRectHook(int* params);
int MkanimRectHook(int* params);
int FilmDoorRectHook(int* params);
int TechDoorRectHook(int* params);
int MedalPositionHook(int* params);
int MedalDescriptionHook(int* params);
int KalidorCrescentPosition1Hook(int* params);
int KalidorCrescentPosition2Hook(int* params);
int GetRankPointsArrayPtr();
int GetPilotRatingPointsArrayPtr();
int MedalAndKalidorCrescentDescriptionHook(int* params);
int PlayPerMissionMovieHook(int* params);
int WritePilotHook(int* params);
int ReadPilotHook(int* params);
int CreatePilotHook(int* params);
int ReadEmailTxtHook(int* params);
int SetupConcourseStarfieldHook(int* params);
int DrawConcourseStarfieldHook(int* params);
int SwitchFrontPlanetImageHook(int* params);
int LoadFrontPlanetImageHook(int* params);
