<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Version>1.0.0.0</Version>
    <ProductName>XWA hook patcher</ProductName>
    <Description>Hook_Patcher</Description>
    <Company>Jérémy Ansel</Company>
    <Copyright>Copyright © 2025 Jérémy Ansel</Copyright>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
    <VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <SelfContained>true</SelfContained>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <NoWarn>CS0649</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JeremyAnsel.Xwa.ExePatcher" Version="1.0.5" />
    <PackageReference Include="JeremyAnsel.Xwa.HooksConfig" Version="1.0.12" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="BeforeBeforeBuild" BeforeTargets="BeforeBuild">
    <SetBuildNumber>
      <Output TaskParameter="AssemblyVersion" PropertyName="Version" />
    </SetBuildNumber>
  </Target>
  <UsingTask TaskName="SetBuildNumber" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v4.0.dll">
    <ParameterGroup>
      <AssemblyVersion ParameterType="System.String" Output="true" />
    </ParameterGroup>
    <Task>
      <Code Type="Fragment" Language="cs">
        <![CDATA[
        DateTime date = DateTime.Now;
        string dateDot = date.ToString("yyyy.MMdd.HHmm.ssfff");
        AssemblyVersion = dateDot;
        ]]>
      </Code>
    </Task>
  </UsingTask>

  <Target Name="PublishAsBuildAfterTarget" AfterTargets="Build" DependsOnTargets="Publish">
    <!-- placeholder task to force Publish to happen during build -->
  </Target>

</Project>
