#pragma once

#include <string>

enum MsgId
{
	ID_MSG_SFOILS_CLOSING_1,
	ID_MSG_SFOILS_CLOSING_2,
	ID_MSG_SFOILS_OPENING_1,
	ID_MSG_SFOILS_OPENING_2,
	ID_MSG_SFOILS_CLOSED_1,
	ID_MSG_SFOILS_CLOSED_2,
	ID_MSG_SFOILS_OPEN_1,
	ID_MSG_SFOILS_OPEN_2,
	ID_MSG_NOT_EQUIPPED_SFOIL_1,
	ID_MSG_NOT_EQUIPPED_SFOIL_2,
	ID_MSG_NOT_EQUIPPED_SFOIL_3,
	ID_MSG_NOT_EQUIPPED_LANDINGGEARS_1,
	ID_MSG_NOT_EQUIPPED_LANDINGGEARS_2,
	ID_MSG_NOT_EQUIPPED_LANDINGGEARS_3,
	ID_MSG_SFOILS_NO_FIRE,
	ID_MSG_HANGAR_TRACTOR_1,
	ID_MSG_HANGAR_TRACTOR_2,
	ID_MSG_HANGAR_TRACTOR_3,
	ID_MSG_HANGAR_TRACTOR_4,
	ID_MSG_ASK_ABOUT_HYPER_1,
	ID_MSG_ASK_ABOUT_HYPER_2
};

const char* Translate(const std::string& language, MsgId id);
